### ISSUE TITLE
Only resolve promise/success callback if status code returned is 200

### ISSUE THREAD

**Issue by vernak2539** [salesforce-marketingcloud/FuelSDK-Node-Auth#46]
At the moment, the promise is only rejected/callback returns error if the request module returns an error. 

This should change to follow more with the API, having only 200 statuses resolve/callback success, and all others reject/callback error

**Comment by vernak2539** [comment]
@dougwilson do you think this is a good idea?

**Comment by dougwilson** [comment]
So the `superagent` module actually just started doing this and I think it's a net positive, because I'm sure we all know how lame it is to keep verifying the status code (or, usually, don't bother and blow up in weird ways when it's an error ;) ). So I'm :+1:
